# driver-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: sonumondal1998/driver-service:latest
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  selector:
    app: driver-service
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30081
  type: NodePort
