# stop-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stop-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stop-service
  template:
    metadata:
      labels:
        app: stop-service
    spec:
      containers:
        - name: stop-service
          image: sonumondal1998/stop-service:latest
          ports:
            - containerPort: 7100
---
apiVersion: v1
kind: Service
metadata:
  name: stop-service
spec:
  selector:
    app: stop-service
  ports:
    - protocol: TCP
      port: 7100
      targetPort: 7100
      nodePort: 30082
  type: NodePort
